development: &development
  adapter: postgresql
  encoding: unicode
  database: cleaning_duty_app_development
  pool: 5
  username: postgres
  password:
  min_messages: warning

test:
  <<: *development
  database: cleaning_duty_app_test
